### ISSUE TITLE
[Question] Question about MPOA output files (.masked.dm.fasta vs .masked.fasta)

### ISSUE THREAD

**Issue by llk578496** [replikation/MPOA#11]
Hi @replikation,

We really appreciate MPOA's contribution to improving ONT-only bacterial genome assembly accuracy during outbreak investigations.

Regarding the output files: Could you please clarify which file represents the final masked genome - .masked.dm.fasta or .masked.fasta?

Thank you very much!

Best regards,
Eddie

**Comment by maralohde** [comment]
Hi Eddie,
Thank you for your kind feedback. 

The **.masked.fasta** is the genome with solely masked ambiguous positions. 

With **.masked.dm.fasta** (depth masking), in addition to the ambiguous positions, positions with a low sequencing depth are masked with N following the `--depth` option flag (Masks regions with a sequencing depth below X with N's [default: 10]). 

Best regards,
Mara

**Comment by llk578496** [comment]
Hi @maralohde ,

Thank you for your prompt reply!

Best regards,
Eddie
